hide s3tokens under lifesaver middleware
sapcc/keystone-extensions pull request #7
Opened 2023-12-01 13:40 UTC by bbobrov

2023-12-01 16:30 UTC, stanislav-zaprudskiy requested changes

2023-12-01 16:30 UTC, stanislav-zaprudskiy commented on cc/keystone/middleware/lifesaver.py
> +                    body.get('ec2Credentials')
```suggestion
                    body.get('credentials') or
                    body.get('ec2Credentials')
```

2023-12-01 17:08 UTC, bbobrov commented on cc/keystone/middleware/lifesaver.py
> +                    body.get('ec2Credentials')
there is indeed a mistake here

2023-12-01 17:08 UTC, bbobrov commented on cc/keystone/middleware/lifesaver.py
> +                    body.get('ec2Credentials')
https://github.com/openstack/keystone/blob/master/keystone/api/_shared/EC2_S3_Resource.py#L80-L93

2023-12-04 08:10 UTC, stanislav-zaprudskiy approved these changes

2023-12-07 14:35 UTC, bbobrov commented
I have tested this in qa-de-3 and it works. However, it might be good to cover /ec2tokens API with this code as well, because it might also flood us. Let me do it...

2023-12-08 14:47 UTC, stanislav-zaprudskiy approved these changes
🚀

2023-12-13 09:57 UTC, merged